### ISSUE TITLE
DIMS: MongoDB ingest status persistence

### ISSUE THREAD

**Issue by GPortas** [harvard-lts/HDC#104]
Once the DIMS interaction with the actual MQs has been developed, we need to persist the different states in MongoDB during the ingest process, so that this state can be queried by DVN later.

**Comment by ives1227** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HDC-62163f60fb08c60011fa4795/issues/harvard-lts/HDC/104?planning-poker) with ZenHub @GPortas @jessjass

**Comment by GPortas** [comment]
PR: https://github.com/harvard-lts/drs-import-management-service/pull/19

**Comment by ives1227** [comment]
Resolution: https://github.com/harvard-lts/drs-import-management-service/commit/23b0632161135bca8ae327848e8c7dfc80d2ac2f
