### ISSUE TITLE
DIMS: advanced ingest POST controller

### ISSUE THREAD

**Issue by GPortas** [harvard-lts/HDC#105]
The goal is to evolve the current /ingest endpoint, which does not manage any request body, so that it includes the request body necessary for DVN to connect and create an ingest in a secure way.

API definitions: https://docs.google.com/document/d/1Q3KqCRlmcyrQfQxfCYWLUAKSs9DTOj9yp3m4ovrRA7w/edit#heading=h.hreo56n7vc4a

Dependencies: @qqmyers for possible design decisions and testing the integration of DVN-DIMS

**Comment by awoods** [comment]
@GPortas : This is important functionality. I will put it in the sprint, but let's make sure the flow of messaging across the components works as the first priority. Thanks.
