### ISSUE TITLE
Implement API to receive Archiving status messages in Dataverse

### ISSUE THREAD

**Issue by qqmyers** [harvard-lts/HDC#113]
per design discussions/docs

**Comment by sbiver** [comment]
Has been verified by curl. Additional step is to verify it through the ingest controller.

**Comment by qqmyers** [comment]
curl -X PUT -H 'Content-Type:application/json' -d '{"status":"pending","message":"I thought about this one too"}' -H 'X-Dataverse-key:81d3ddac-a21a-4413-9251-0231d8e9ef90' http://localhost:8080/api/admin/submitDatasetVersionToArchive/:persistentId/1.15/status?persistentId=doi:10.5072/FK2/E6CMKR
{"status":"OK","data":{"message":"Status updated"}}
curl -X PUT -H 'Content-Type:application/json' -d '{"status":"success","message":"http://nowhere.com/not/really/done"}' -H 'X-Dataverse-key:81d3ddac-a21a-4413-9251-0231d8e9ef90' http://localhost:8080/api/admin/submitDatasetVersionToArchive/:persistentId/1.14/status?persistentId=doi:10.5072/FK2/E6CMKR
{"status":"OK","data":{"message":"Status updated"}}
curl -H 'Content-Type:application/json' -H 'X-Dataverse-key:81d3ddac-a21a-4413-9251-0231d8e9ef90' http://localhost:8080/api/admin/submitDatasetVersionToArchive/:persistentId/1.14/status?persistentId=doi:10.5072/FK2/E6CMKR
{"status":"OK","data":{"status":"success","message":"http://nowhere.com/not/really/done"}}

nowhere.com
Domain im Kundenauftrag registriert
Domain registriert bei united-domains.de
:thankyou_green:
1

10:23
You can see the popup for m=pending and the link for the success message at http://dvn-dev-hdc.lib.harvard.edu/dataset.xhtml?persistentId=doi:10.5072/FK2/E6CMKR / version table.

**Comment by qqmyers** [comment]
API key has to be changed for the curl commands above to work
