### ISSUE TITLE
Create import service project code base

### ISSUE THREAD

**Issue by adaybujeda** [harvard-lts/HDC#13]
Initialize Flask / Python Project code base.

- [x] 1. Setup base dependencies and configuration
- [x] 2. Provide basic /health endpoint 
- [x] 3. Make application executable
- [x] 4. Create initial Docker Configuration for IMS Deployment

DoD:
- Deploy first version of Flask App

**Comment by GPortas** [comment]
Java skeleton code base (done before deciding to switch to python): https://github.com/GPortas/import-management-service/tree/HDC-13-service-skeleton-java

**Comment by GPortas** [comment]
PR: https://github.com/harvard-lts/drs-import-management-service/pull/2
