### ISSUE TITLE
Refactoring HDC/LDN message in DASH

### ISSUE THREAD

**Issue by awoods** [harvard-lts/HDC#132]
..based on recent COAR discussions.

**Comment by sbiver** [comment]
duplicate from DSpace 31

**Comment by sbiver** [comment]
Pending conversation with COAR Notify on final decision.

**Comment by awoods** [comment]
PR under review: https://github.com/harvard-lts/DSpace/pull/53

**Comment by awoods** [comment]
Resolved with: https://github.com/harvard-lts/DSpace/commit/48aed2393ff65a783c70c143ac242202d473e1ce
