### ISSUE TITLE
DVN Goal: have instance running for user feedback

### ISSUE THREAD

**Issue by awoods** [harvard-lts/HDC#136]

**Comment by qqmyers** [comment]
http://dvn-qa-hdc.lib.harvard.edu/ is running with 3A/3B code. Since the QA versions of DASH/archiving aren't up, it isn't fully functional yet.

**Comment by sbiver** [comment]
We are ready to test the integration of all the microservices in QA. @qqmyers will need to publish a dataset for the team to test. https://harvard-huit.slack.com/archives/C031UUVK2HY/p1652480367367389
@jessjass

**Comment by sbiver** [comment]
@jessjass , @qqmyers , since DASH NRS-QA setup is resolved, are we in a place to close this ticket too?

**Comment by sbiver** [comment]
Once DIMS is talking to Dataverse in QA (either manually, or once integration tests pass) we can close this ticket.
