### ISSUE TITLE
DRS Ingest - Opaque and Opaque Container relationship validation

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/HDC#158]
DRS Project JIRA Story: https://jira.huit.harvard.edu/browse/LIBDRS-8648
This story is a placeholder to track the work completed in the DRS

As a DVN or ePADD depositor, I would expect the data that I ingest to contain any type of relationship defined (in OTS).  Right now, the relationships are restricted but with with the changes in the content models defined in this [document|https://docs.google.com/document/d/1asiDJRpnAHZaCfY_AVFsERwRuEUONqyr/edit?usp=sharing&ouid=109345449805985432358&rtpof=true&sd=true,] the relationship validation needs to be modified.

Per discussion with Chris, Jessi, and Dee Dee:

The RelationshipValidationBean.validateRelationshipContentModels method should be updated to return true if the sourceCm is Opaque or Opaque Container
The static methods should be removed but documented in the static call at the beginning of the class to describe why there is not an init call (all relationships are valid for these content models and the check is handled in the validate call from #1): 
initOpaqueRules()
initOpaqueContainerRules()

**Comment by jessjass** [comment]
PR: https://github.huit.harvard.edu/LTS/drs2_services/pull/66

**Comment by jessjass** [comment]
Resolved with: https://github.huit.harvard.edu/LTS/drs2_services/commit/bda28102e2e5538668b29551601af63a2e255734
