### ISSUE TITLE
Add hdc3a-tansfer-service to Jenkins and HDC3A-IF

### ISSUE THREAD

**Issue by jessjass** [harvard-lts/HDC#197]
# Definition of Done
   - hdc3a-tansfer-service is deployed to Dev and QA with Jenkins

## Testing
   - confirm deployments on Dev and QA are working 

# Dependencies
   - None

**Comment by jessjass** [comment]
PR: https://github.huit.harvard.edu/LTS/HDC3A-IF/pull/13

**Comment by ives1227** [comment]
Resolution: https://github.huit.harvard.edu/LTS/HDC3A-IF/commit/5a7fbaf5d2d80e359a89274b0a85775c94de65c5
