### ISSUE TITLE
Implement Single Archived Version Semantics in Dataverse

### ISSUE THREAD

**Issue by qqmyers** [harvard-lts/HDC#198]
The current Dataverse code  manages archival submission and status display for different dataset versions independently. Conversely, in the MVP timeframe, DRS will only support archiving of a single dataset version. This issue proposes changing Dataverse to support single archival version semantics. Under the hood, this requires some extension so that archivers (DRS, DuraCloud, Google, etc.) can indicate whether they are single version or not and updating the Workflow, API and UI:

Workflow:
- submit version for archiving API: does nothing (writes a log message) if any other version of the dataset has a non-null archiving status

API changes:
- POST submit version for archiving API: returns an error (e.g. 409 Conflict) if any other version of the dataset has a non-null archiving status
  -  this is true regardless of whether the status is pending/failure/success
- PUT archiving status: returns a failure (e.g. 409) if any other version of the dataset has a non-null archiving status
 - DELETE - (no change) used to remove the status of the specified version which, for single version, would then allow this or another version to be submitted for archiving
  - Optionally could create a DELETE API call that doesn't require specifying the version since there can be only one (would need to define semantics for multi-version case - does it delete all?)

UI Changes:
No Archived version/no status:
- All dataset version rows show 'Submit' for an admin
- All dataset version rows show 'Not Archived' for a normal user
One version has a status (i.e. one was submitted and is either pending or is a failure/success)
- Admin sees status as is for this version (with popup showing pending/failure details or as a link to the DRS page for success) and 'Not Archived' for all other versions
- Normal user sees basic pending/failure/success label (no details/no actions) for the one version and 'Not Archived' for all others

Implications:
- When an admin hits 'Submit' for some version, it updates to show a status (e.g. pending) and all other rows change to 'Not Archived'
- Once a version has been submitted, there is no UI mechanism to delete it, clear a failure, etc. An admin can use the API to delete the status, or some other part of the system could call the API to reset the status and allow the admin to submit another  version.
- The automated workflow (if enabled) would submit the version being published if and only if no earlier version had been published (i.e. there would be no failure w.r.t. the ingest/further processing step returning a failure status, there would just be no submission to start with).
- Future changes to enable archiving multiple versions, or (elsewhere in the community) moving/reconfiguring the dataset to use a multi-version-capable archiver would work - the single version rules would just not apply
- Going from a multiversion-capable archiver to a single version one would be ~problematic/ill-defined since more than one version could have a status.
  - Rules can probably be written to ~handle this, e.g. if there are multiple versions with status, those are all displayed, but new archiving can't be started without clearing all versions with a status.
- As with the current multiple version implementation, if archiving is turned off, the UI will still show if there is a version with an archival status but there will be no UI means to submit new versions. Datasets with no archived versions would not show the archival column at all.

**Comment by awoods** [comment]
Thanks, @qqmyers . This looks good.
Comments:
1 
> Optionally could create a DELETE API

We can likely forgo this option for now.


2
> The automated workflow (if enabled)

Given the recent conversation, I would suggest disabling automated versioning for now.

**Comment by sbarbosadataverse** [comment]
@qqmyers just so I am clear---this still allows all versions of a dataset to show in the versions tab as it does now and only impacts this preservation version status, correct? thanks

**Comment by qqmyers** [comment]
Yes - this is only about the archive status column

**Comment by sbarbosadataverse** [comment]
Then it looks great to me. Thanks

**Comment by sbiver** [comment]
Copying here Stephen Abrams' comment from slack:

**Comment by sbiver** [comment]
@qqmyers Can this implementation still happen as part of this sprint?
