### ISSUE TITLE
Provision LTS S3 bucket

### ISSUE THREAD

**Issue by awoods** [harvard-lts/HDC#2]

**Comment by awoods** [comment]
@ives1227 : You should be able to provision the S3 bucket without others on the team having VPN access yet, no?

**Comment by ives1227** [comment]
@awoods yes - this ticket was submitted to Ops yesterday.

**Comment by ives1227** [comment]
[INC04412889](https://harvard.service-now.com/incident.do?sys_id=75b3df801b06095045dca8a8b04bcbac&sysparm_record_target=task&sysparm_record_row=7&sysparm_record_rows=11&sysparm_record_list=active%3Dtrue%5Esys_class_name%21%3Drm_product%5Eu_requester%3Djavascript%3Ags.getUserID%28%29%3B%5EORDERBYnumber)

**Comment by ives1227** [comment]
Credentials emailed and placed in LPE
