### ISSUE TITLE
DLQ Handler Service: Admin notifications for DLQ message handling events

### ISSUE THREAD

**Issue by GPortas** [harvard-lts/HDC#217]

**Comment by GPortas** [comment]
PR: https://github.com/harvard-lts/hdc3a-dlq-handler-service/pull/6

**Comment by ives1227** [comment]
Resolution: https://github.com/harvard-lts/hdc3a-dlq-handler-service/commit/dccf3a5e99c8fec8df14c54fc23247feb76379c9
