### ISSUE TITLE
DASH - NRS-QA setup

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/HDC#218]
- _We need to set up HDCQA to use NRS QA._

- _Link this issue with and existing epic._

- Ideally, the issue is phased as a user story, e.g.
   > As a depositor I can deposit and get a real NRS handle, so that I can actually have a stable handle

# Definition of Done
   - NRS QA is set up and tested as working in QA

## Testing
   - William will have to do a test deposit and confirm we have the right NRS link

# Dependencies
   - Not that I know of

**Comment by sbiver** [comment]
@wwelling , @dl-maura Are we ready to close this ticket?

**Comment by dl-maura** [comment]
our test worked so I say yes!
