### ISSUE TITLE
Create Project Close-out documentation

### ISSUE THREAD

**Issue by sbiver** [harvard-lts/HDC#228]
The documentation is described in the [dev notes](https://docs.google.com/document/d/1qiL9yC7fBiAzubL5hLYzHsSt3LdXFH4kPbcIESolrCo/edit#bookmark=id.1dqpkhvsz0v0) and will live in the dedicated [google folder](https://drive.google.com/drive/folders/1V710MLYnZ8-W4Ev2BKAKBWccwtP6s_CO).

**Comment by awoods** [comment]
Resolved with: https://docs.google.com/document/d/1EpHIhNhBlV2ccUZhMdXh7MrC4fiIJhqfH5iJ2S5XmvY/edit?usp=sharing
