### ISSUE TITLE
DIMS & HDHS documentation

### ISSUE THREAD

**Issue by GPortas** [harvard-lts/HDC#232]

**Comment by GPortas** [comment]
DIMS documentation link: https://docs.google.com/document/d/1UMLZywvg3WBXkbq2J39YBXf2T_CYVu5IftzN9J_CHGs/

**Comment by GPortas** [comment]
HDHS documentation link:
https://docs.google.com/document/d/1gUoEkKE6Qvu1TcaEhv5vE81PBuo6QkEutw36J1_k7rg/

**Comment by awoods** [comment]
Nice work, @GPortas .
I have added comments to both documents.
