### ISSUE TITLE
Batch Builder: Permit designation of the new roles for deposits under the OPAQUE and OPAQUE CONTAINER content models

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/HDC#24]
As a Dataverse depositor, I would expect Batch Builder to accommodate the necessary roles and content model type for my data.  Content Model descriptions can be found here: https://drive.google.com/drive/u/2/folders/1MenEduYHi-O8XiMPVcnKbOq-qTM15Apn

**Comment by ives1227** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HDC-62163f60fb08c60011fa4795/issues/harvard-lts/HDC/24?planning-poker) with ZenHub @GPortas @jessjass

**Comment by ives1227** [comment]
From Paul A:
1. When trying to set a file level 'ROLE' to 'COLOR PROFILE' for an Opaque Object, I get an error:
`No enum constant edu.harvard.hul.ois.ots.schemas.HulDrsAdminMD.DrsFileMD.Role.COLOR_PROFILE`
2.  I didn't see the new 'HAS_PREVIOUS_VERSION' object relationship available in the Opaque Container list in the GUI
3,  There are no file relationships available for assignment for Opaque Containers CM in the BatchBuilder GUI
Question: Is there a complete list of Roles and Relationships that should be available? I know both Opaque and Opaque Container should have all of them, but I almost missed the HAS_PREVIOUS_VERSION because it is new and I didn't notice it right away when I read the content model guide.
Thanks!

**Comment by ives1227** [comment]
COLOR_PROFILE is not available for file-level.  It is an error that it is still in BB - I will fix that.
2. I know there are numerous relationships that were not supported by BB and I think this came up in a different conversation with Stephen Abrams.  So I will ask Stephen, does BB need to support every possible relationship for MVP or do we want to leave it as is and users will have to make updates via Web Admin once ingested? What about the new HAS_PREVIOUS_VERSION?
3. I will look and see what is going on with that.

**Comment by ives1227** [comment]
Changes made.  Based on this slack thread: https://harvard-huit.slack.com/archives/C031UUVK2HY/p1653483708279239

**Comment by ives1227** [comment]
From Paul A today:
I’ve finished testing the Opaque and Opaque Containers in BB.  I’ll do some quick checks on other CMs but I wanted to share the few remaining things I found.
 
Opaque content model:
file-to-file relationships not available in documentation directory in GUI.  File-to-file for documentation does work with CLI options
 
Opaque Container:
Everything seems fine including the file-to-file relationships
 
Thought: It may be worth limiting the identifier type for files to the DRS File ID.  In the DRS WebAdmin, there’s not an option to enter anything else for files.  The new BB allows Delivery URNs and File OSNs, but according to Chris, DRS uses the File ID behind the scenes anyway.  Not every file has a delivery URN, and Chris said that even if the delivery URN were deleted from the file, the relationship would remain because of the File ID.  It’s not urgent. Just a thought.

**Comment by ives1227** [comment]
From Paul A regarding CLI:
I was trying out the BB CLI with relationships that can have a multiple values, and I found some odd behavior.  It looks like BB creates two entries for each property=value.
 
In the example below, has_subset can have multiple values, but in the descriptor, there are two entries for the DRS ID and two entries for the URN.
 
I admit to not being as confident on CLI.  I may be using the wrong syntax.  If you can see what I should be using, I’ll try that too.  This may very well have been an existing problem.
Thanks
Paul
 
 
Ex:
batchbuildercli -a build -p "E:\DRS_DEV_BB_test_projects\BB_2_3_0_HDC\Opaque_objects" -b batch_opaque_HDC_CLI_2 -objectprop opaque_HDC_CLI_25may2022::has_source=400170409,has_target=urn-3:HUL.DRS.OBJECT:33067517,has_subset=400170409,has_subset=urn-3:HUL.DRS.OBJECT:33067517,has_presentation=400170409,has_presentation=urn-3:HUL.DRS.OBJECT:33067517[https://app.zenhub.com/files/462873645/d761cd23-ae86-4a66-9328-63733b52afed/download](https://app.zenhub.com/files/462873645/d761cd23-ae86-4a66-9328-63733b52afed/download)

**Comment by ives1227** [comment]
Both of these issues have been corrected and sent back to Paul A for testing.

**Comment by ives1227** [comment]
Removed OBJECT_DESCRIPTOR from BB and cut another snapshot release - @pablothemoose

**Comment by pablothemoose** [comment]
Successfully loaded object 400309720 into Dev using new BB Snapshot that removed the option for OBJECT_DESCRIPTOR role for files. WebAdmin still allows role to be added, but that's another story.

**Comment by ives1227** [comment]
@pablothemoose do you think your testing is complete for this?

**Comment by pablothemoose** [comment]
It is still possible to add OBJECT_DESCRIPTOR role to files using the CLI:
batchbuildercli -a build -p "E:\DRS_DEV_BB_test_projects\BB_2_3_0_HDC\Opaque_objects"  -b batch_opaque_HDC_3 -dirprop opaque_HDC_02jun2022_C::content::filerole=OBJECT_DESCRIPTOR

Is that difficult to remove because it's in the OTS definition?

**Comment by ives1227** [comment]
@pablothemoose I created a story in the DRS JIRA board: https://jira.huit.harvard.edu/browse/LIBDRS-8776.  I think that the setting of the OBJECT_DESCRIPTOR file role is highly unlikely and that can be moved to a post-MVP story.  

cc - @awoods
