### ISSUE TITLE
OTS: Permit new roles for OPAQUE and OPAQUE CONTAINER content models

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/HDC#25]
As a Dataverse depositor, I would expect OTS to accommodate the necessary roles in the Opaque and Opaque Container content models for my data. Content Model descriptions can be found here: https://drive.google.com/drive/u/2/folders/1MenEduYHi-O8XiMPVcnKbOq-qTM15Apn

**Comment by awoods** [comment]
Based on [2022-03-09 conversation](https://docs.google.com/document/d/1pmc1y7XMgQ8gCZKuW6bxGDTv0cCpsqdRXkqY4rmOn48/edit?pli=1#), this should include setting storage-class at the file-level.

**Comment by ives1227** [comment]
@awoods this story is actually for updating the opaque/opaque container content model, not the storage classes.  The storage classes are already at file-level in OTS.  Once we have the storage class meeting in April, we can figure out whether the ability to set storage class on a file-by-file basis should live (BB or ingest).  Note: storage class is already at the file-level but does not currently have a way to do it on a file-by-file basis.

**Comment by awoods** [comment]
Thanks, @ives1227 . Feel free to create a new ticket now as a placeholder for the file-by-file assignment of storage-classes, or you can wait until after the April meeting.

**Comment by ives1227** [comment]
PR: https://github.huit.harvard.edu/LTS/ots/tree/HDC-25

**Comment by jessjass** [comment]
Resolved with: https://github.huit.harvard.edu/LTS/ots/commit/ea33d559b130109da913f34c2112e6804b91d903
