### ISSUE TITLE
Temporarily Disable EAS Deposits

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/HDC#62]
DRS JIRA ticket: https://jira.huit.harvard.edu/browse/LIBDRS-8370

**Comment by awoods** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HDC-62163f60fb08c60011fa4795/issues/harvard-lts/HDC/62?planning-poker) with ZenHub @jessjass

**Comment by ives1227** [comment]
Julie is testing in QA

**Comment by ives1227** [comment]
Resolution: https://github.huit.harvard.edu/LTS/eas/commit/fa07ca6168d6a342cfa94d3b772ec23a60b9ab23
