### ISSUE TITLE
DTS: Set up cron job to monitor dropbox

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/HDC#63]
As a developer, I will need to know if an ingest has failed or succeeded.  The way to determine this is via the Load Report that is deposited into the dropbox.  A cron job will have to be added to periodically check for a the Load Report.

Once the load report is detected, it should call a DTS API defined here: https://docs.google.com/document/d/1Q3KqCRlmcyrQfQxfCYWLUAKSs9DTOj9yp3m4ovrRA7w/edit#

**Comment by ives1227** [comment]
https://github.com/harvard-library/aspace_pyscripts

**Comment by jessjass** [comment]
Resolved with commit: https://github.com/harvard-lts/hdc3a-cron/commit/92a58bdac4c353e794b234c12d7848091a4dbfa3
