### ISSUE TITLE
OTS: Accommodate the HAS_PREVIOUS_VERSION relationship in the Opaque and Opaque Container content models

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/HDC#66]
As a Dataverse depositor, I would expect OTS to accommodate the HAS_PREVIOUS_VERSION relationship in the Opaque and Opaque Container content models for my data. Content Model descriptions can be found here: https://drive.google.com/drive/u/2/folders/1MenEduYHi-O8XiMPVcnKbOq-qTM15Apn

**Comment by awoods** [comment]
I believe the exact DRS versioning approach is still an open question. Suggest to hold off on this ticket until that has been decided... likely post-MVP.
