### ISSUE TITLE
Setup: Deployment environment

### ISSUE THREAD

**Issue by sbiver** [harvard-lts/HDC#74]
As and HDC developer, I need a `dev` environment wherein all of the all of the system components are deployed so that when functional code is being developed, it has a pre-established environment in which to be run. 

[System diagram](https://drive.google.com/file/d/1pXzL4_9ejLg3QUprGO6Ts3i-9aPAiHgb/view?usp=sharing) depicting necessary components.

Acceptance criteria:
All of the following components are deployed within the LTS VPN
1. All queues are provisioned: process queue, transfer queue, DRS queue
1. Mongo DB is provisioned
1. Shared S3 bucket is provisioned
1. EFS dropbox is provisioned
1. Out of the box Dataverse is installed

**Comment by jessjass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HDC-62163f60fb08c60011fa4795/issues/harvard-lts/HDC/74?planning-poker) with ZenHub @GPortas @ives1227
