### ISSUE TITLE
Setup: Jenkins

### ISSUE THREAD

**Issue by sbiver** [harvard-lts/HDC#75]
As an HDC developer, I need a CI/CD pipeline that is triggered on commits and pull-requests so that I know that the application tests pass, that the application successfully deploys, and so that I have a deployed system with which to experiment.

Acceptance criteria:
1. Deployed and configured CI/CD pipeline that monitors the drs-import-management-service and drs-translation-service code bases
1. The pipeline must create Docker images for the above projects
1. The pipeline must deploy the [HDC3A-IF](https://github.huit.harvard.edu/LTS/HDC3A-IF) project into the `dev` (and eventually `QA`) environment
1. The pipeline must run the project integration tests
1. The pipeline must notify the team if any of the steps above fail

**Comment by jessjass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HDC-62163f60fb08c60011fa4795/issues/harvard-lts/HDC/75?planning-poker) with ZenHub @GPortas @ives1227
