### ISSUE TITLE
Infrastructure plumbing: Messaging clients

### ISSUE THREAD

**Issue by sbiver** [harvard-lts/HDC#80]
As an HDC developer, I need to have "hello world" messaging producer and consumer clients as a part of the dims and drs-translation-service components, so that the team has confidence that these components will be able to integrate into the system architecture.

**Comment by jessjass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HDC-62163f60fb08c60011fa4795/issues/harvard-lts/HDC/80?planning-poker) with ZenHub @GPortas @ives1227
