### ISSUE TITLE
Dataverse workflow: Config changes

### ISSUE THREAD

**Issue by sbiver** [harvard-lts/HDC#82]
As a Dataverse installation administrator, I need to be able to configure (and unconfigure) the individual collections within the Dataverse installation to automatically preserve datasets.

**Comment by jessjass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HDC-62163f60fb08c60011fa4795/issues/harvard-lts/HDC/82?planning-poker) with ZenHub @GPortas @ives1227
