### ISSUE TITLE
Content staging: Status communication

### ISSUE THREAD

**Issue by sbiver** [harvard-lts/HDC#88]
As an on-going step in the preserve process, the Dataverse application must poll the DIMS API after the preservation process has been initiated, so that the current archiving status may be rendered in the Dataverse UI.

**Comment by jessjass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HDC-62163f60fb08c60011fa4795/issues/harvard-lts/HDC/88?planning-poker) with ZenHub @GPortas @ives1227
