### ISSUE TITLE
Create basic Translation Service Docker image

### ISSUE THREAD

**Issue by awoods** [harvard-lts/HDC#9]
As a developer, I will need the translation service to run in a Docker container on the cloud servers.  This requires setting up the application so that it connects to the various queues on startup.

**Comment by ives1227** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HDC-62163f60fb08c60011fa4795/issues/harvard-lts/HDC/9?planning-poker) with ZenHub @jessjass @GPortas @awoods

**Comment by ives1227** [comment]
https://github.com/harvard-lts/drs-translation-service/commit/f1e2f149e44aca1a82017abdc6ee3cfc9316396b
