### ISSUE TITLE
DRS ingest: Updates to OTS

### ISSUE THREAD

**Issue by sbiver** [harvard-lts/HDC#91]
As a step in the preservation process, the OTS library must be updated to support the Opaque Research Data content model, so that a DRS batch can be created from a Dataverse export bag.

This will likely include updating BatchBuilder and/or WebAdmin:
1. To permit new roles for OPAQUE and OPAQUE CONTAINER content models
1. To permit XML or JSON files or other registered MIME type (if known) or application/octet-stream (if unknown) 
1. To permit object deposits with only documentation files, but not primary content files

See: [DRS/ePADD/HDC Master Plan](https://docs.google.com/document/d/1pmc1y7XMgQ8gCZKuW6bxGDTv0cCpsqdRXkqY4rmOn48/edit?usp=sharing)

**Comment by jessjass** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HDC-62163f60fb08c60011fa4795/issues/harvard-lts/HDC/91?planning-poker) with ZenHub @GPortas @ives1227
